### Freshwater fish Trade Correct for 
### and print the file



### Aggregate fish consumption to countries (fw and !=low confidence) ------

# set vector of columns to summarize
vars <- c('consump_million.tons.yr', 'consump_million.tons.yr_fwaes', 
          'consump_million.tons.yr_fwaes_mf50','consump_million.tons.yr_fwaes_mf50_rng')

# aggregate the fish products to countries
consump_nat_agg_df <- consump_df %>%
        
        # keep only freshwater and mixed source products for 
        # countries of high confidence.
        filter(Freshwater..F..or.Marine..M. != 'M',
               Confidence != 'Low') %>%
        
        # sum the consumption per country
        group_by(country, country_code, year_start, grp) %>%
        summarise_each_(funs(sum(. , na.rm=TRUE)), vars)

# remove the variable vector
rm(vars)



### Join imports, exports, aquaculture and catch to consumption data -----------

# run script that formats the trade data 
source('./fishstatj_data/read_nat_fw_trade_data.R', print.eval = TRUE)
source('./fishstatj_data/read_nat_aquaculture_data.R', print.eval = TRUE)
source('./fishstatj_data/read_nat_catch_data.R', print.eval = TRUE)

# delete df generated by sourced scripts that are not needed
#rm(aq, aq_inl, ca)

# filter to only freshwater catch
aq_sum_bycountry <- aq_sum_bycountry %>% filter(source == 'Inland')
ca_sum_bycountry <- ca_sum_bycountry %>% filter(source == 'Inland')


# execute left join (only keep the consump countries)
consump_nat_agg_df <- 
  
  left_join(consump_nat_agg_df, aq_sum_bycountry, 
            by = c("country_code" = "country_code", "year_start" = "year")) %>%
  
  left_join(. , tr_sum_bycountry, 
            by = c("country_code" = "country_code", "year_start" = "year")) %>%
  
  left_join(. , ca_sum_bycountry, 
            by = c("country_code" = "country_code", "year_start" = "year"))


# change the empty rows (NA) to 0
vars <- c('Import', 'Export', 'sum_aquacul')
consump_nat_agg_df <- consump_nat_agg_df %>% ungroup() %>%
  mutate_each_(funs(ifelse(is.na(.), 0, .)), vars)


# Delete duplicated columns
drop_cols <- c('source.x', 'source.y','CountryCountry.x', 
               'CountryCountry.y', 'type.x', 'type.y')
consump_nat_agg_df <- consump_nat_agg_df %>% dplyr::select(-one_of(drop_cols))


# remove temp data from env
rm(aq, aq_inl, ca, drop_cols, vars, 
   ca_sum_bycountry, aq_sum_bycountry, tr_sum_bycountry)



### Correct the consumption with import/export and aquaculture  ------------------------


# convert trade to millions of tons and remove effect on consumption
consump_nat_agg_df <- consump_nat_agg_df %>%
  
  # convert values to millions of tons as new column
  mutate(sum_import_millions = Import / 1000000,
         sum_export_millions = Export / 1000000,
         sum_aquacult_millions = sum_aquacul / 1000000,
         sum_catch_millions = sum_catch / 1000000,
         
         # account for the contribution of trade and aquaculture
         consump_million.tons.yr_fwaes_mf50_noimp = 
           consump_million.tons.yr_fwaes_mf50 - sum_import_millions + sum_export_millions - sum_aquacult_millions) %>%
  
  # remove conlumns expressed in tons 
  dplyr::select(-one_of(c('Import', 'Export','sum_aquacul', 'sum_catch')))



### Join the LIFDC list to the table -------------------------------------------

# read the table with LIFDC codes
lifdc_df <- read.csv('../data/lifd_country_list.csv', stringsAsFactors = FALSE)

# create binary sting column describing if LIFDC or not
lifdc_df <- mutate(lifdc_df,lifd_2015=ifelse(is.na(lifd_2015),'not LIFDC','LIFDC'))

# add country code to lifdc and join it to nat table
lifdc_df$country_code <- countrycode(lifdc_df$country,'country.name','iso3c', warn=TRUE)
consump_nat_agg_df <-  left_join(consump_nat_agg_df, lifdc_df, by='country_code')

# add continent column to the nat agg table
consump_nat_agg_df$continent <- countrycode(consump_nat_agg_df$country_code,'iso3c','continent',warn=TRUE)
consump_nat_agg_df$country <- countrycode(consump_nat_agg_df$country_code,'iso3c','country.name',warn=TRUE)
consump_df$country <- countrycode(consump_df$country_code,'iso3c','country.name',warn=TRUE)

# remove temporary df from env
rm(lifdc_df)



### Write the table to csv file ------------------------------------------------
write.csv(consump_df, '../output/consumption/hh_survey_consump_sep_prods_fw.csv')
write.csv(consump_nat_agg_df, '../output/consumption/hh_survey_consump_nat_agg_prod_fw.csv')

