# This script intakes the consumed products, ajoined by the expert coding
# and removes the 

# Combine output of agg prod into a single df 
library(dplyr)


#### TODOs:
# - unify the reading of trade FishStatJ file into a single script-function
#   using a filenames as input
# - Move the reading of catch and aquaculutre files outside the loop, and rename the filtered version


### Read input files -----------------------------------------------------------
# read the code-assigned product list
consump_df <- read.csv('../output/consumption/hh_survey_consump_sep_prods.csv',
                       stringsAsFactors=FALSE)


# filt the filtering condition and associated tables
# filtering conditions are separated on the product source
filt_cond <- read.csv('./consumption/cond.csv', stringsAsFactors=FALSE)



### Aggregate fish consumption to countries ----------------------------------
# loop through the rows of the filt_cond table, 
# using the inputs as arguements for filtering
# ** aggregate the fish products to countries
for (i in 1:nrow(filt_cond)){
  
  # ** Declare a vector of columns to summarize -----------------
  vars <- c('consump_million.tons.yr', 
            'consump_million.tons.yr_fwaes', 
            'consump_million.tons.yr_fwaes_mf50',
            'consump_million.tons.yr_fwaes_mf50_rng')
  
  
  ### ** filtering table based on filtering condition --------------
  consump_df_temp <- consump_df %>%
      # for code simplicity, convert all medium conf_lvls into high 
      # (could be revisited at some point) 
      mutate(confidence_lvl = ifelse(confidence_lvl=='medium', 'high', confidence_lvl)) %>%
  
      # filter by source AND confidence lvl
      filter(
        # split the piped sources from file to vector for filtering
        prod_src_fm %in% c(unlist(strsplit(filt_cond[i,'src_cond'], split="\\|"))) & 
        confidence_lvl == (filt_cond[i,'conf_cond'])) 
    
   ### ** Aggregate products to national total -----------------------------
   consump_nat_agg_df <- consump_df_temp %>%
         # sum the consumption per country
          group_by(country.x, country_code, year_start, grp, confidence_lvl) %>%
          summarise_each_(funs(sum(. , na.rm=TRUE)), vars) %>%
          ungroup() %>%
          filter(consump_million.tons.yr > 0) %>%
          mutate(prod_src = filt_cond[i,'src_cond'])
  
  
  ### Join imports, exports, aquaculture and catch to consumption data -----------
  # run script that formats the trade data exported from FishStatJ
  # because the F/M selection cannot be accomplished outside of FishStatJ 
  source(filt_cond[i,'trade_file'], print.eval = TRUE)
  
  
  ### ** source scripts reading aquaculture and catch --------------------------------
  # as these are common across F/M
  source('./fishstatj_data/read_nat_aquaculture_data.R', print.eval = TRUE)
  source('./fishstatj_data/read_nat_catch_data.R', print.eval = TRUE)
  
  # delete df generated by sourced scripts that are not needed
  rm(aq, aq_inl, ca)

  # split
  src_cond_fishstatj_splt <- c(unlist(strsplit(filt_cond[i,'src_cond_fishstatj'], split="\\|"))) 
  
  # ** filter aquaculture and catch data ---------------------------- 
  # to the filtering condition; wanted: 1 sum row per cntry per yr
  aq_sum_bycountry <- aq_sum_bycountry %>% 
                      filter(source %in% src_cond_fishstatj_splt) %>%
                      group_by(country_code, CountryCountry, year, type) %>% 
                      summarise(sum_aquacul = sum(sum_aquacul))
  
  ca_sum_bycountry <- ca_sum_bycountry %>% 
                      filter(source %in% src_cond_fishstatj_splt) %>%
                      group_by(country_code, CountryCountry, year, type) %>% 
                      summarise(sum_catch = sum(sum_catch))


  # execute left join (only keep the consump countries)
  consump_nat_agg_df <- 
    
    left_join(consump_nat_agg_df, aq_sum_bycountry, 
              by=c("country_code"="country_code","year_start"="year")) %>%
    
    left_join(. , tr_sum_bycountry, 
              by=c("country_code"="country_code","year_start"="year")) %>%
    
    left_join(. , ca_sum_bycountry, 
              by=c("country_code"="country_code","year_start"="year"))
  
  # remove temp data from env
  rm(ca_sum_bycountry, aq_sum_bycountry, tr_sum_bycountry)
  
  
  # change the empty rows (NA) to 0
  vars <- c('Import', 'Export', 'sum_aquacul')
  consump_nat_agg_df <- consump_nat_agg_df %>% ungroup() %>%
    mutate_each_(funs(ifelse(is.na(.), 0, .)), vars)
  
  
  # Delete duplicated columns
  drop_cols <- c('source.x', 'source.y','CountryCountry.x', 
                 'CountryCountry.y', 'type.x', 'type.y')
  consump_nat_agg_df <- consump_nat_agg_df %>% dplyr::select(-one_of(drop_cols))
  
  
  
  ### Correct the consumption with import/export and aquaculture  ------------------------
  
  # convert trade to millions of tons and remove effect on consumption
  consump_nat_agg_df <- consump_nat_agg_df %>%
    
    # convert values to millions of tons as new column
    mutate(sum_import_millions = Import / 10^6,
           sum_export_millions = Export / 10^6,
           sum_aquacult_millions = sum_aquacul / 10^6,
           sum_catch_millions = sum_catch / 10^6,
           
           # account for the contribution of trade and aquaculture
           consump_million.tons.yr_fwaes_mf50_noimp = 
             consump_million.tons.yr_fwaes_mf50 - sum_import_millions + sum_export_millions - sum_aquacult_millions) %>%
    
    # remove conlumns expressed in tons 
    dplyr::select(-one_of(c('Import', 'Export','sum_aquacul', 'sum_catch')))


  
  ### Join LIFDC, continent, etc to sep and agg prod consump dfs --------------
  
  # read the table with LIFDC codes
  lifdc_df <- read.csv('../data/lifd_country_list.csv', stringsAsFactors = FALSE)
  
  # create binary sting column describing if LIFDC or not
  lifdc_df <- mutate(lifdc_df,lifd_2015=ifelse(is.na(lifd_2015),'not LIFDC','LIFDC'))
  
  # add country code to lifdc and join it to nat table
  lifdc_df$country_code <- countrycode(lifdc_df$country,'country.name','iso3c', warn=TRUE)
  consump_nat_agg_df <-  left_join(consump_nat_agg_df, lifdc_df, by='country_code')
  
  # add continent column to the nat agg table
  consump_nat_agg_df$continent <- countrycode(consump_nat_agg_df$country_code,'iso3c','continent',warn=TRUE)
  consump_nat_agg_df$country <- countrycode(consump_nat_agg_df$country_code,'iso3c','country.name',warn=TRUE)
  consump_df_temp$country <- countrycode(consump_df_temp$country_code,'iso3c','country.name',warn=TRUE)
  
  # remove temporary df from env
  rm(lifdc_df)
  

  ### Write the table to csv file ------------------------------------------------
  t <- filt_cond[i,'filename_suffix']
  path <- '../output/consumption/prod_coded_n_agg/'
  write.csv(consump_df_temp, 
            paste(path,'hh_survey_consump_sep_prods_',t,'.csv',sep=''))
  write.csv(consump_nat_agg_df, 
            paste(path,'hh_survey_consump_nat_agg_prod_',t,'.csv',sep=''))

}




### Combine agg prod files into one -----------------------
# declare directory to look into
file_path <- "../output/consumption/prod_coded_n_agg/"
# list all files in the path, and matching the pattern
agg_files <- list.files(path= file_path, pattern= 'agg')

# combine the files into one df
agg_files_combined <- do.call(`rbind`,lapply(paste(file_path,agg_files,sep=''), 
                                             read.csv, header=T))
# write combined df to new file
write.csv(agg_files_combined, paste(file_path,'hh_survey_consump_nat_agg_prod_combined.csv',sep=''))


