# This script joins consumption with ca, aq, tr on a prodcut-by-product basis.


### import libraries -----------------------------------------------------------
library(stringdist)
library(fuzzyjoin)
library(dplyr)
library(tidyr)
options("scipen"=100, "digits"=4)

# set working directory
setwd("C:/Users/efluet/Dropbox/chap5_global_inland_fish_catch/scripts")



### read the table to csv file ------------------------------------------------
consump_prods <- read.csv('../output/consumption/hh_survey_consump_sep_prods.csv', stringsAsFactors=FALSE)

consump_prods <-  consump_prods %>%
                  filter(confidence_lvl == 'high' |
                         confidence_lvl == 'medium') %>%
                  filter(prod_src_fm == 'F' |
                         prod_src_fm == 'F/M') %>%
                  #select(-one_of('country_code.x','prod_name.distance','country_code.distance')) %>%
                  mutate(consump_yr_fwaes_mf50 = consump_million.tons.yr_fwaes_mf50 * 10^6) %>%
                  select(country_code, year_start, prod_name, consump_yr_fwaes_mf50)


### Clean up the product name: remove 'nei', remove the processing names fresh, dried, cured, etc.

# create string of words to remove from fish product names
rm_str <- 'dried|smoked|salted|chilled|nei|and|of|séché|fumé|fraise|fresco|frozen|preserved|fermented'
#fish|Fish|poisson|Poisson|pescado|autres|autros|otros|peixe|outros|fresh|

consump_prods <- consump_prods %>%
  # Remove word fish from strings of both tables to improve match
  mutate(prod_name_mod = gsub(rm_str," ", prod_name)) %>%
  # substitute some punctionation for spaces to improve splits in some cases.
  mutate(prod_name_mod = gsub("[[:punct:]]", " ", prod_name_mod)) %>%
  # create empty product column where matches will be written 
  mutate(product = NA)





### produce list of distinct products ----------------------------------------
consump_prods_cntry_yr <- consump_prods %>% 
                          select(country_code, year_start) %>%
                          distinct()


# read the product data for catch, aquaculture and  trade ----------------------
source('./consumption/data_proc/read_ca_aq_tr_sep_prod_data.r')
# delete df generated by sourced scripts that are not needed
rm(ca, aq_sum_bycountry, aq, tr, ca_sum_bycountry, tr_sum_bycountry)



### loop through countries -----------------------------------------------------
for (i in seq(consump_prods_cntry_yr$country_code)) {
  
  
  # ** subset to country of current loop ---------------------------------------
  aq_inl_temp <- aq_inl %>% filter(country_code == consump_prods_cntry_yr[i,'country_code'])
  ca_inl_temp <- ca_inl %>% filter(country_code == consump_prods_cntry_yr[i,'country_code'])
  tr_inl_temp <- tr_inl %>% filter(country_code == consump_prods_cntry_yr[i,'country_code'])
  consump_prods_temp <- consump_prods %>% filter(country_code == consump_prods_cntry_yr[i,'country_code'])
  
  
  #### CATCH AND AQUACULTURE SHOULD BE JOINED
  
  # 1. Fuzzy string join consumption with fao catch ----------------------------------------
  consump_df_temp <- stringdist_full_join(consump_prods_temp, ca_inl_temp, 
    by = c(prod_name_mod='SpeciesASFISspecies'), max_dist=20, distance_col="distance_ca")
  
  # clean up joined table consump-ca
  consump_df_temp <- consump_df_temp %>%
    mutate(country_code.x=ifelse(is.na(country_code.x), country_code.y, country_code.x)) %>% 
    select(-country_code.y) %>%
    arrange(country_code.x) %>%
    mutate(prod_name= ifelse(is.na(prod_name), SpeciesASFISspecies, prod_name),
           prod_name_mod= ifelse(is.na(prod_name_mod), SpeciesASFISspecies, prod_name_mod))

  # if no match is made during stringdist, the distance field is added manually
  if (class(consump_df_temp$distance_ca) == "NULL" ){
    consump_df_temp <- consump_df_temp %>% mutate(distance_ca = NA)}
  
  
  
  # 2. Fuzzy string join consumption with aquaculture ----------------------------------------
  consump_df_temp <- stringdist_full_join(consump_df_temp, aq_inl_temp, 
    by = c(prod_name_mod='SpeciesASFISspecies'), max_dist=4, distance_col="distance_aq")
  
  # clean up joined table consump-ca
  consump_df_temp <- consump_df_temp %>%
    mutate(country_code.x=ifelse(is.na(country_code.x), country_code, country_code.x)) %>% 
    select(-country_code) %>%
    arrange(country_code.x) %>%
    mutate(prod_name= ifelse(is.na(prod_name), SpeciesASFISspecies.y, prod_name),
           prod_name_mod= ifelse(is.na(prod_name_mod), SpeciesASFISspecies.y, prod_name_mod))

  # if no match is made during stringdist, the distance field is added manually
  if (class(consump_df_temp$distance_aq) == "NULL" ){
    consump_df_temp <- consump_df_temp %>% mutate(distance_aq = NA)}
  
  
  

  # 3. Fuzzy string join consumption with trade ----------------------------------------
  consump_df_temp <- stringdist_full_join(consump_df_temp, tr_inl_temp, 
    by = c(prod_name_mod='CommodityCommodity'), max_dist=4, distance_col="distance_tr")
  
  
  # clean up joined table consump-ca
  consump_df_temp <- consump_df_temp %>%
    mutate(country_code.x=ifelse(is.na(country_code.x), country_code, country_code.x)) %>% 
    #select(-country_code.y) %>%
    arrange(country_code.x) %>%
    mutate(prod_name= ifelse(is.na(prod_name), CommodityCommodity, prod_name),
           prod_name_mod= ifelse(is.na(prod_name_mod), CommodityCommodity, prod_name_mod))
    
  # if no match is made during stringdist, the distance field is added manually
  if (class(consump_df_temp$distance_tr) == "NULL" ){
    consump_df_temp <- consump_df_temp %>% mutate(distance_tr = NA)}

  
  # for the first loop create output df  
  if (i==1) { consump_df <- consump_df_temp 
  # otherwise 
  } else { consump_df <- rbind(consump_df, consump_df_temp)}
  
}




# remove 
consump_df <- consump_df %>%
              select(-one_of('CountryCountry.x','CountryCountry.y','Reexport','EnvironmentEnvironment'))

# remove temporary df
rm(consump_df_temp, aq_inl_temp, ca_inl_temp, tr_inl_temp, consump_prods_temp, consump_prods_cntry_yr)

### write outpute --------------------------------
write.csv(consump_df, '../output/consumption/hh_survey_consump_sep_prods_with_ca_aq_tr.csv')





  
  count_consump_prod_name <-  consump_df %>%
                              filter(prod_name == consump_df_temp[i,'prod_name'])
  
  count(where )
}



### ------------------------------------
cleanup<-function (x){
  
  if (nb prod A > 1 & nb_prod_b > 1) {
    
    remove row with largest distance
    
  }
  # get the count of the 
  count_consump_prod_name <- consump_df %>%
                             filter(prod_name == prod_name)
  
}



# if (class(consump_df_temp$distance) != "NULL" ){
#   ### Select a single closest matching code and country, for each product ----------
#   consump_df_temp <- consump_df_temp %>%
#                 group_by(SpeciesASFISspecies) %>%
#                 filter(distance == min(distance) | is.na(distance)) %>%
#                 ungroup() 






#consump_df <- union(consump_prods, ca_inl, by = c(country_code = "country_code"))#, prod_name='SpeciesASFISspecies'))
### 
consump_df <- full_join(consump_prods, ca_inl, by = c(country_code = "country_code"))#, prod_name='SpeciesASFISspecies'))
consump_df <- consump_df %>%
              mutate(prod_name.distance = stringdist(prod_name, SpeciesASFISspecies)) %>%
              group_by(country_code, prod_name) %>%
              filter(prod_name.distance == min(prod_name.distance) | is.na(prod_name.distance)) 



# split
src_cond_fishstatj_splt <- c(unlist(strsplit(filt_cond[i,'src_cond_fishstatj'], split="\\|"))) 

# ** filter aquaculture and catch data ---------------------------- 
# to the filtering condition; wanted: 1 sum row per cntry per yr
aq_sum_bycountry <- aq_sum_bycountry %>% 
  filter(source %in% src_cond_fishstatj_splt) %>%
  group_by(country_code, CountryCountry, year, type) %>% 
  summarise(sum_aquacul = sum(sum_aquacul))

ca_sum_bycountry <- ca_sum_bycountry %>% 
  filter(source %in% src_cond_fishstatj_splt) %>%
  group_by(country_code, CountryCountry, year, type) %>% 
  summarise(sum_catch = sum(sum_catch))
