# This script joins consumption with ca, aq, tr on a prodcut-by-product basis.


### import libraries -----------------------------------------------------------
library(stringdist)
library(fuzzyjoin)
library(dplyr)
library(tidyr)
options("scipen"=100, "digits"=4)

# set working directory
setwd("C:/Users/efluet/Dropbox/chap5_global_inland_fish_catch/scripts")



### read the table to csv file ------------------------------------------------
consump_prods <- read.csv('../output/consumption/hh_survey_consump_sep_prods_fwaes_uncert.csv', 
                          stringsAsFactors=FALSE)


consump_prods <-  consump_prods %>%
                  # select products by confidence level and source code
                  filter(confidence_lvl == 'high' | confidence_lvl == 'medium',
                         prod_src_fm == 'F' | prod_src_fm == 'F/M') %>%
                  #select(-one_of('country_code.x','prod_name.distance','country_code.distance')) %>%
                  #mutate(consump_yr_fwaes_mf50 = consump_million.tons.yr_fwaes_mf50 * 10^6) %>%
                  select(country_code, year_start, prod_name)#, consump_yr_fwaes_mf50)


### Clean up the product name: remove 'nei', remove the processing names fresh, dried, cured, etc.

# create string of words to remove from fish product names
rm_str <- 'dried|smoked|salted|chilled|nei|and|of|séché|fumé|fraise|fresco|frozen|preserved|fermented'
#fish|Fish|poisson|Poisson|pescado|autres|autros|otros|peixe|outros|fresh|

# Remove word fish from strings of both tables to improve match
# substitute some punctionation for spaces to improve splits in some cases.
consump_prods <-  consump_prods %>%
                  mutate(prod_name_mod= gsub(rm_str," ", prod_name)) %>%
                  mutate(prod_name_mod= gsub("[[:punct:]]", " ", prod_name_mod))



### produce list of distinct products ----------------------------------------
consump_prods_cntry_yr <- consump_prods %>% 
                          select(country_code, year_start) %>%
                          distinct()



### read the product data for catch, aquaculture and  trade ----------------------
source('./consumption/data_proc/read_ca_aq_tr_sep_prod_data.r')
# delete df generated by sourced scripts that are not needed
rm(ca, aq_sum_bycountry, aq, tr, ca_sum_bycountry, tr_sum_bycountry)



### loop through countries 
for (i in seq(consump_prods_cntry_yr$country_code)) {
  
  
  # ** subset to country of current loop ---------------------------------------
  aq_inl_temp <- aq_inl %>% filter(country_code == consump_prods_cntry_yr[i,'country_code'])
  ca_inl_temp <- ca_inl %>% filter(country_code == consump_prods_cntry_yr[i,'country_code'])
  tr_inl_temp <- tr_inl %>% filter(country_code == consump_prods_cntry_yr[i,'country_code'])
  consump_prods_temp <- consump_prods %>% filter(country_code == consump_prods_cntry_yr[i,'country_code'])
  
  
  
  ### 1.1 Fuzzy string join consumption with fao catch ----------------------------------------
  ca_aq_inl_temp <- stringdist_full_join(ca_inl_temp, aq_inl_temp, 
    by = c(SpeciesASFISspecies='SpeciesASFISspecies'), max_dist=2, distance_col="distance_ca_aq")
  
  ### 1.2 clean up joined table consump-ca
  ca_aq_inl_temp <- ca_aq_inl_temp %>%
    mutate(country_code.x=ifelse(is.na(country_code.x), country_code.y, country_code.x)) %>%
    mutate(SpeciesASFISspecies.x = ifelse(is.na(SpeciesASFISspecies.x), SpeciesASFISspecies.y, SpeciesASFISspecies.x)) %>%
    select(-one_of('CountryCountry','SpeciesASFISspecies.y','country_code.y','distance_ca_aq')) %>%
    arrange(country_code.x) %>%
    mutate(SpeciesASFISspecies.x = tolower(SpeciesASFISspecies.x)) %>%
    select(country_code.x, SpeciesASFISspecies.x, catch, production)

  
  
  # 2.1  create string of words to remove from fish product names
  rm_str <- 'dried|smoked|salted|chilled|nei|and|of|séché|fumé|fraise|fresco|frozen|preserved|fermented|fresh|or|fillets'
  #fish|Fish|poisson|Poisson|pescado|autres|autros|otros|peixe|outros|fresh|
  
  tr_inl_temp <- tr_inl_temp %>%
    mutate(CommodityCommodity = tolower(CommodityCommodity)) %>%
    # Remove word fish from strings of both tables to improve match
    mutate(CommodityCommodity_mod = gsub(rm_str," ", CommodityCommodity)) %>%
    # substitute some punctionation for spaces to improve splits in some cases.
    mutate(CommodityCommodity_mod = gsub("[[:punct:]]", " ", CommodityCommodity_mod)) 

  
  
  
  # 2.2 Fuzzy string join trade with fao catch&aquaculture ---------------------
  # other methods : lcs, qgram
  ca_aq_tr_inl_temp <- stringdist_full_join(ca_aq_inl_temp, tr_inl_temp, 
                        by = c(SpeciesASFISspecies.x='CommodityCommodity_mod'), 
                        method='lcs', max_dist=4, distance_col="distance_ca_aq")

  
  # 2.3 clean up joined table consump-ca-aq-tr
  ca_aq_tr_inl_temp <- ca_aq_tr_inl_temp %>%
    # fill country_code column
    mutate(country_code.x=ifelse(is.na(country_code.x), country_code, country_code.x)) %>%
    # fill product name 
    mutate(SpeciesASFISspecies.x = ifelse(is.na(SpeciesASFISspecies.x), CommodityCommodity, SpeciesASFISspecies.x)) %>%
    # remove columns
    select(-one_of('CommodityCommodity','country_code')) %>%
    arrange(country_code.x) 
  
  
  
  
  # 3.1  Fuzzy string join fao stats to consumption  ----------------------------------------
  consump_df_temp <- stringdist_full_join(consump_prods_temp, ca_aq_tr_inl_temp,
                     by = c(prod_name_mod='SpeciesASFISspecies.x'), 
                     max_dist=0, distance_col="distance_consump_fao")

  # 3.2  clean up joined table consump-ca
  consump_df_temp <- consump_df_temp %>%
              mutate(country_code.x=ifelse(is.na(country_code.x), 
                                           country_code, country_code.x)) %>%
              select(-country_code) %>%
              arrange(country_code.x) %>%
              mutate(prod_name= ifelse(is.na(prod_name), SpeciesASFISspecies.x, prod_name),
                     prod_name_mod= ifelse(is.na(prod_name_mod), SpeciesASFISspecies.x, prod_name_mod))

  # 3.3. if no match is made during stringdist, the distance field is added manually
  if (class(consump_df_temp$distance_consump_fao) == "NULL" ){
    consump_df_temp <- consump_df_temp %>% mutate(distance_consump_fao = NA)}
  

  
  # for the first loop create output df  
  if (i==1) { consump_joined_df <- consump_df_temp 
  # otherwise add rows to existing output df
  } else { consump_joined_df <- rbind(consump_joined_df, consump_df_temp)}
  
}

consump_joined_df <- consump_joined_df[1,3,2,4]


# remove temporary df
rm(consump_df_temp, aq_inl_temp, ca_inl_temp, tr_inl_temp, consump_prods_temp, consump_prods_cntry_yr)

### write outpute --------------------------------
write.csv(consump_joined_df, '../output/consumption/hh_survey_consump_sep_prods_with_ca_aq_tr.csv')

